<?php
/**
 * Created by PhpStorm.
 * User: xuliulei
 * Date: 18-8-22
 * Time: 下午4:49
 */

namespace app\admin\controller;

use app\admin\common\Util;
use app\admin\db\CDBAccount;
use think\Controller;
use think\Request;

class Base extends Controller
{

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $controller = Request::instance()->controller();
        $action = Request::instance()->action();
        include_once APP_PATH.'admin/filter/'.$controller.'.php';

        if (in_array($action,$whiteList)){
            $CDBAccount = new CDBAccount();
            if (!$CDBAccount->isLogin()) {
                Util::printResult($GLOBALS['ERROR_LOGIN'], '登录错误');
                exit;
            }
        }
    }

}