<?php

$whiteList = [
    'slideShow_v1/add',
    'slideShow_v1/edit',
    'slideShow_v1/delById',
    'categoryManagement_v1/add',
    'categoryManagement_v1/edit',
    'categoryManagement_v1/del',
    'labelManagement_v1/add',
    'labelManagement_v1/edit',
    'labelManagement_v1/del',
    'newsCategory_v1/add',
    'newsCategory_v1/edit',
    'newsCategory_v1/del',
    'news_v1/add',
    'news_v1/edit',
    'news_v1/del',
    'companyManagement_v1/add',
    'companyManagement_v1/edit',
    'companyManagement_v1/del',
    'positionManagement_v1/add',
    'positionManagement_v1/edit',
    'positionManagement_v1/del',
    'positionManagement_v1/isHot',
];