<?php

namespace app\api\controller\v1;

use app\api\controller\Auth;
use think\Controller;

/**
 * 接口安全验证
 * Class AuthBase
 * @package app\api\controller\v1
 */
class AuthBase extends Controller
{
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $auth = new Auth();
        $auth->respond();
    }
}